name: Running the shell Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Listing the files
        run: |
          pwd
          ls -ltr
        shell: bash

      - name: Make the script executable
        run: chmod +x .github/workflows/test.sh
        shell: bash
      
      - name: Running the Script
        run: ./.github/workflows/test.sh
        shell: bash
